Часть 1.  Оценка аудитории продукта
mikstime/highload pull request #1
Opened 2020-09-29 22:21 UTC by mikstime

2020-10-04 16:24 UTC, init commented on README.md
> +Наличии государственной поддержки, а также увеличение цифролизации
опечатка "цифролизации"

2020-10-04 17:28 UTC, init requested changes

2020-10-04 17:28 UTC, init commented on README.md
> +Грубо говоря почти все данные уменьшатся в 10 раз.
можно это убрать, если всех обязали то норм, в любом случае вы такую нагрузку должны держать на случай "второй волны"

2020-10-04 17:28 UTC, init commented on README.md
> +итоговая аудитория проекта составляет **36 млн человек**.
замечания:
1) среди молодежи проникновение около 100%
2) обязать можно только резидентов РФ

2020-10-04 17:28 UTC, init commented on README.md
> +36\*273/365 ~ **27 млн. чел**
тут грубейшая ошибка, ваши пользователи должны пользовать сервисом каждый рабочий день (все уники)

2020-10-04 17:28 UTC, init commented on README.md
> +стоит сделать более подробный анализ видео трафика.
если большинство уроков это видео - у вас фактически будет видео-хостинг по нагрузке, остальными типами ресурсов действительно можно пренебречь

2020-10-04 17:28 UTC, init commented on README.md
> +Тогда текстовый материал весит около Кб, 10 картинок – 3Мб, 10 минут full hd видео – 500мб.
3-х часовая лекция по моему курсу занимает всего 150-250 Мб, посмотрите размер среднего урока на платформах-аналогах для большей точности расчетов

2020-10-04 17:28 UTC, init commented on README.md
> +Пусть около 6% от активных пользователей будут в это время использовать сервис.
непонятный расчет, если взять население по часовым зонам то пиковые будут соседними и точно больше 6%

2020-10-28 20:04 UTC, mikstime commented on README.md
> +Тогда текстовый материал весит около Кб, 10 картинок – 3Мб, 10 минут full hd видео – 500мб.
Я проверил, час full hd видео занимает 3гб. Я посмотрел пару лекций, они в начале имеют неплохое качество, а потом почему-то дико шакалятся до качества 240p-480p. (По крайней мере Мейл их в таком качестве показывает).

К сожалению я не смог найти данных для образовательных платформ, поэтому взял данные ютуба и нетфликса, там в целом примерно такой объем. По идее, лекции имеют большую схожесть кадров относительно среднего видео с ютьюба, так что можно попробовать поделить битрейт/вес в 2 раза

2020-11-18 19:07 UTC, merged